# Generated by Django 4.2.6 on 2023-10-10 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internshipapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='place',
        ),
    ]
