# Generated by Django 4.2.6 on 2023-10-10 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internshipapp', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pic', models.ImageField(upload_to='img')),
                ('about', models.TextField()),
            ],
        ),
    ]
